// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:afedd062-1c8e-42f9-ad6b-0a5d957c50f9",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_MQZ44876Q",
    "aws_user_pools_web_client_id": "2l2ccc4dbm1ggsa66644f5gc0v",
    "oauth": {
        "domain": "streamingtranscribea5a6160bf-5a6160bf-prod.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://speakintongues.sonasher.com/,https://speakintongues.sonasher.com/",
        "redirectSignOut": "https://speakintongues.sonasher.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "predictions": {
        "convert": {
            "translateText": {
                "region": "us-east-1",
                "proxy": false,
                "defaults": {
                    "sourceLanguage": "en",
                    "targetLanguage": "hi"
                }
            },
            "speechGenerator": {
                "region": "us-east-1",
                "proxy": false,
                "defaults": {
                    "VoiceId": "Aditi",
                    "LanguageCode": "en-IN"
                }
            }
        }
    }
};


export default awsmobile;
