// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b6f089f8-f878-42de-afad-2d040330a77d",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_NJux5EhlE",
    "aws_user_pools_web_client_id": "1pikpa9kb5crhnjida5vhjgocl",
    "oauth": {
        "domain": "streamingtranscribea5a6160bf-5a6160bf-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "predictions": {
        "convert": {
            "translateText": {
                "region": "us-east-1",
                "proxy": false,
                "defaults": {
                    "sourceLanguage": "en",
                    "targetLanguage": "hi"
                }
            },
            "speechGenerator": {
                "region": "us-east-1",
                "proxy": false,
                "defaults": {
                    "VoiceId": "Aditi",
                    "LanguageCode": "en-IN"
                }
            }
        }
    }
};


export default awsmobile;
